#server.port=8001
#
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/productdb
#spring.datasource.username=root
#spring.datasource.password=getoffer
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8051


spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nvsoftware/spring-service-config
          clone-on-start: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8050/eureka}

